#!/bin/bash

echo "=========================================="
echo "🔍 KIỂM TRA VÀ SỬA LỖI"
echo "=========================================="
echo ""
echo "📝 Các bước đã làm:"
echo "  ✓ Thêm method public attendance_action_change()"
echo "  ✓ Method có self.ensure_one() để đảm bảo gọi đúng"
echo ""
echo "🔧 BẠN CẦN LÀM:"
echo ""
echo "1. Vào Odoo: Settings > Apps"
echo ""
echo "2. BẬT DEVELOPER MODE:"
echo "   Settings > Developer Tools > Activate"
echo ""
echo "3. Vào Apps > Xóa filter 'Installed'"
echo ""
echo "4. Tìm và UPGRADE theo thứ tự:"
echo "   a) hdi_hr_attendance_geolocation"
echo "   b) hdi_attendance"
echo ""
echo "5. Sau khi upgrade, RESTART Odoo:"
echo "   - Stop Odoo server (Ctrl+C)"
echo "   - Start lại"
echo ""
echo "6. Kiểm tra lại bằng cách vào console trình duyệt và chạy:"
echo "   await this.orm.call('hr.employee', 'attendance_action_change', [[1]])"
echo ""
echo "=========================================="
echo "💡 QUAN TRỌNG:"
echo "   Module phải được UPGRADE + RESTART Odoo"
echo "   mới nhận method mới!"
echo "=========================================="
