#!/bin/bash

echo "🔍 Hướng dẫn debug lỗi XML view:"
echo ""
echo "1. Xem Odoo log:"
echo "   tail -f /var/log/odoo/odoo.log"
echo "   # Hoặc nếu chạy manual:"
echo "   # Log sẽ hiện trong terminal"
echo ""
echo "2. Tìm dòng ERROR hoặc WARNING liên quan đến:"
echo "   - 'NoneType'"
echo "   - 'view'"
echo "   - 'ngsd_base'"
echo ""
echo "3. Nếu thấy tên view cụ thể, comment view đó trong __manifest__.py"
echo ""
echo "4. Hoặc chạy Odoo với debug mode:"
echo "   ./odoo-bin -c odoo.conf -d your_db -u ngsd_base --log-level=debug"
echo ""
echo "5. Temporary workaround: Disable tất cả views trừ security"
echo "   ✅ Đã làm rồi!"
echo ""
echo "📋 Current manifest data:"
grep -A 30 "'data':" /workspaces/HDI/ngsd/ngsd_base/__manifest__.py | grep -v "^#"

