#!/bin/bash
echo "=========================================="
echo "HƯỚNG DẪN UPGRADE MODULE"
echo "=========================================="
echo ""
echo "Code đã được sửa xong! Bây giờ cần upgrade module."
echo ""
echo "CÁCH 1: Qua giao diện Odoo (KHUYẾN NGHỊ)"
echo "----------------------------------------"
echo "1. Mở Odoo trong trình duyệt"
echo "2. Vào: Settings > Apps"
echo "3. Tìm: 'hdi_hr_attendance_geolocation'"
echo "4. Click: Upgrade"
echo "5. Tìm: 'hdi_attendance'"
echo "6. Click: Upgrade"
echo "7. Refresh trang và thử lại"
echo ""
echo "CÁCH 2: Bật Developer Mode"
echo "----------------------------------------"
echo "1. Settings > Developer Tools > Activate the developer mode"
echo "2. Apps > Remove 'Installed' filter"
echo "3. Search: hdi_hr_attendance_geolocation"
echo "4. Click: Upgrade"
echo "5. Search: hdi_attendance"
echo "6. Click: Upgrade"
echo ""
echo "=========================================="
echo "Files đã được sửa:"
echo "  ✓ hdi_hr_attendance_geolocation/models/hr_employee.py"
echo "  ✓ hdi_attendance/models/hr_employee.py"
echo "=========================================="
