{
    'name': 'NGSD Menu',
    'summary': '(TT)☞ Entrust Consulting (TT)',
    'author': 'Entrust Consulting Co., LTD',
    'license': 'LGPL-3',
    'depends': ['ngsd_base', 'ngs_attendance', 'sale_timesheet', 'ngsd_crm', 'helpdesk', 'account', 'account_reports', 'sales_team', 'crm', 'sale', 'project', 'hr_timesheet', 'hr', 'hr_contract','hr_skills', 'resource', 'ngs_hr'],
    'data': [
        'views/home.xml',
        'views/website_views.xml',
        'views/menu.xml',
        'views/qlbh.xml',
        'views/qlda.xml',
        'security/kpi.xml',
        'security/contract.xml',
        'security/invoice.xml',
        'security/payment.xml',
        'security/global.xml',
        'security/extra.xml',
        'security/ir.model.access.csv',
        'security/group_tpvh.xml',
        'security/group_tptc.xml',
        'security/group_tpkndu.xml',
        'security/group_tvda.xml',
        'security/group_pm.xml',
        'security/group_qam.xml',
        'security/group_qal.xml',
        'security/group_gdkndu.xml',
        'security/group_gdkv.xml',
        'security/group_userhr.xml',
        'security/group_tk.xml',
        'security/group_tppmo.xml',
        'security/group_vpm.xml',
        'security/group_sale.xml',
        'security/group_td.xml',
    ],
    "assets": {
        "web.assets_common": [
            "ngsd_menu/static/src/scss/form.scss",
        ],
    },
    'auto_install': False,
    'application': True,
    'installable': True,
}
