from . import approve
from . import res_partner
from . import base
from . import res_users
from . import email_data
from . import res_company
from . import hr_employee
from . import x_customer_group
from . import x_customer_category
from . import kpi_kpi
from . import kpi_detail
from . import res_config_settings
from . import hr_name_only_models
from . import project_project
from . import resource_planning
from . import hr_overtime
from . import hr_overtime_type
from . import project_task
from . import problem
from . import crm_lead
from . import en_experience
from . import en_nonproject_task
from . import en_overtime_plan
from . import mail_message
from . import ir_rule
from . import table_criteria_api
from . import hr_boundary
from . import en_quality_control
from . import hr_contract
from . import en_fiscal_year
from . import en_borrow_employee
from . import en_lender_employee
from . import report_data_human
from . import department_resource
from . import en_qa_report_work
from . import lock_license
from . import hr_leave
from . import ir_model_data
