{
    'name': 'NGSD Base',
    'summary': '(☞ﾟヮﾟ)☞ Entrust Consulting (❁´◡`❁)',
    'author': '(☞ﾟヮﾟ)☞ Entrust Consulting (❁´◡`❁)',
    'website': "http://entrustlab.com",
    'depends': [
        'base',
        'documents',
        'product',
        'crm',
        'hr',
        'hr_holidays',
        'project',
        'analytic',
        'sale_timesheet',
        'account',
        'hr_timesheet',
        'sale_management',
        'hr',
        'hr_contract',
        'hr_skills',
        'website',
        'website_blog',
        'web_notify',
        'ngsd_report_xlsx',
        'ngsd_entrust_dev_helper',
        'web_widget_dropdown_dynamic',
        'web_field_o2m_duplicate_row',
        'ngsd_report_docx',
        'hr_recruitment',
        'website_hr_recruitment',
        'hr_org_chart_overview',
        'entrust_access',
        'web_editor',
    ],
    'data': [
        'security/groups.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'data/project_project_stage.xml',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        'data/resource_calendar.xml',
        'data/account_analytic_account.xml',
        'data/account_analytic_line_action.xml',
        'data/en_hr_overtime_action.xml',
        'data/table_criteria_api.xml',
        'views/a.xml',
        'views/res_partner_views.xml',
        'views/message_subtypes.xml',
        'views/email_data.xml',
        'views/res_company.xml',
        'views/x_customer_category.xml',
        'views/x_customer_group.xml',
        'views/kpi_kpi.xml',
        'views/kpi_detail.xml',
        'views/hr_name_only_models.xml',
        'views/problem.xml',
        'views/project_project.xml',
        'views/en_fiscal_year.xml',
        'views/res_config_settings.xml',
        'views/resource_planning.xml',
        'views/hr_overtime.xml',
        'views/hr_overtime_type.xml',
        'views/project_task.xml',
        'views/approve.xml',
        'views/res_users.xml',
        'views/experience.xml',
        'views/en_nonproject_task.xml',
        'views/en_overtime_plan.xml',
        'views/hr_job.xml',
        'views/hr_boundary.xml',
        'views/hr_department.xml',
        'views/en_quality_control.xml',
        'views/hr_contract.xml',
        'views/documents_folder.xml',
        'views/report_data_human_resource.xml',
        'views/en_borrow_employee.xml',
        'views/en_lender_employee.xml',
        'views/hr_leave_type.xml',
        'views/lock_license.xml',
        'views/ngs_leave_allocation.xml',
        'views/en_qa_report_work.xml',
        'views/hr_employee.xml',

        'wizard/message_wizard.xml',
        'wizard/new_version_wbs_wizard.xml',
        'wizard/import_wbs_popup.xml',
        'wizard/message_pơpup_confirm.xml',
        'wizard/leave_project_popup.xml',
        'wizard/en_lender_employee_return_popup.xml',
        'report/report_action.xml',
        'wizard/hr_overview_report_popup.xml',
        'wizard/add_workload_popup.xml',
        'wizard/change_task_timesheet.xml',
        'wizard/change_lock_license.xml',

    ],
    'license': 'LGPL-3',
    "assets": {
        "web.assets_qweb": [
            "ngsd_base/static/src/xml/**/*",
        ],
        "web.assets_common": [
            "ngsd_base/static/src/js/tempusdominus.js",
        ],
        "web.assets_backend": [
            "ngsd_base/static/src/js/*.js",
            "ngsd_base/static/src/scss/*.scss",
        ],
    },
}