{
    'name': 'NGSD Base',
    'summary': '(☞ﾟヮﾟ)☞ Entrust Consulting (❁´◡`❁)',
    'author': '(☞ﾟヮﾟ)☞ Entrust Consulting (❁´◡`❁)',
    'website': "http://entrustlab.com",
    'depends': [
        'base',
        'hr',
        'hr_holidays',
        'hr_contract',
        'hr_skills',
        'account',
        'hr_timesheet',
        'hr_recruitment',
        'hr_org_chart_overview',
        # 'documents',
        # 'product',
        # 'crm',
        # 'project',
        # 'analytic',
        # 'sale_timesheet',
        # 'sale_management',
        # 'website',
        # 'website_blog',
        # 'web_notify',
        # 'ngsd_report_xlsx',
        # 'ngsd_entrust_dev_helper',
        # 'web_widget_dropdown_dynamic',
        # 'web_field_o2m_duplicate_row',
        # 'ngsd_report_docx',
        # 'website_hr_recruitment',
        # 'entrust_access',
        # 'web_editor',
    ],
    'data': [
        'security/groups.xml',
        # 'security/ir_rule.xml',  # Temporarily disabled
        'security/ir.model.access.csv',
        # Temporarily disable most data/views to isolate the error
        # 'data/mail_template.xml',
        # 'data/ir_cron.xml',
        # 'data/ir_sequence.xml',
        # 'data/resource_calendar.xml',
        # 'data/en_hr_overtime_action.xml',
        # 'data/table_criteria_api.xml',
        # 'views/res_partner_views.xml',
        # 'views/message_subtypes.xml',
        # 'views/email_data.xml',
        # 'views/res_company.xml',
        # 'views/hr_name_only_models.xml',
        # 'views/res_config_settings.xml',
        # 'views/hr_overtime.xml',
        # 'views/hr_overtime_type.xml',
        # 'views/res_users.xml',
        # 'views/hr_job.xml',
        # 'views/hr_department.xml',
        # 'views/hr_contract.xml',
        # 'views/hr_leave_type.xml',
        # 'views/ngs_leave_allocation.xml',
        # 'views/hr_employee.xml',

        # 'wizard/message_wizard.xml',
        # 'wizard/new_version_wbs_wizard.xml',
        # 'wizard/import_wbs_popup.xml',
        # 'wizard/message_pơpup_confirm.xml',
        # 'wizard/leave_project_popup.xml',
        # 'wizard/en_lender_employee_return_popup.xml',
        # 'report/report_action.xml',
        # 'wizard/hr_overview_report_popup.xml',
        # 'wizard/add_workload_popup.xml',
        # 'wizard/change_task_timesheet.xml',
        # 'wizard/change_lock_license.xml',

    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
    # Assets temporarily disabled due to Odoo 18 compatibility issues
    # Will be re-enabled after migration to Owl/ES6
    # "assets": {
    #     "web.assets_backend": [
    #         "ngsd_base/static/src/css/*.css",
    #     ],
    # },
}