{
    'name': 'NGSD CRM',
    'summary': '(☞ﾟヮﾟ)☞ Entrust Consulting (❁´◡`❁)',
    'author': '(☞ﾟヮﾟ)☞ Entrust Consulting (❁´◡`❁)',
    'website': "http://entrustlab.com",
    'depends': [
        'ngsd_base',
        'sale',
        'sale_crm',
    ],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'wizard/crm_lead_win_views.xml',
        'data/ir_sequence_data.xml',
        'data/change_data.xml',
        'security/rule.xml',
        'views/crm_lead_views.xml',
        'views/crm_team_views.xml',
        'views/product_category.xml',
        'views/crm_team.xml',
        'views/crm_other_view.xml',
        'views/crm_support_history.xml',
        'views/compete_lead.xml',
        'views/order.xml',
        'views/account_move.xml',
        'views/crm_kpi.xml',
        'views/crm_atta.xml',
        'views/kt_department.xml',
        'views/project_type_source.xml',
        'views/sale_order.xml',
        'views/x_legal.xml',
        'views/x_sale_contract.xml',
        'views/res_partner.xml',
        'views/crm_stage.xml',
        'data/ir_cron.xml',
        'wizard/crm_lead_lost_views.xml',
    ],
    'installable': True,
}