from . import crm_role
from . import crm_tender_model
from . import crm_lead
from . import crm_product_type
from . import crm_lead_line
from . import crm_support_state
from . import crm_lead_contact
from . import crm_lead_opponent
from . import crm_contact_role
from . import product_category
from . import crm_team
from . import crm_support_history
from . import compete_lead
from . import crm_stage
from . import crm_kpi
from . import x_legal
from . import kt_department
from . import project_type_source
from . import sale_order
from . import x_sale_contract
from . import x_payment_schedule
from . import order
from . import res_partner
from . import account_move
from . import res_users
